version = 1

[*]
flash-attn = on

# --- Example chat model ---
; [my-chat-model]
; model = /models/my-chat-model/my-model.gguf
; ctx-size = 8192
; parallel = 2
; repeat-penalty = 1.1
; load-on-startup = true
; mmproj = /models/my-chat-model/mmproj.gguf

# --- Example embedding model ---
; [my-embed-model]
; model = /models/my-embed-model.gguf
; ctx-size = 2048
; parallel = 1
; embeddings = true
; load-on-startup = true